vich_uploader:
  db_driver: orm
  metadata:
    auto_detection: true
    type: attribute
  mappings:
    insuranceClaim_images:
      uri_prefix: '%insuranceClaim_images%'
      upload_destination: '%kernel.project_dir%/public/assets/uploads/sinistres'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
