controllers:
  resource: ../src/Controller/
  type: annotation

kernel:
  resource: ../src/Kernel.php
  type: annotation

# User Profile
umbrella_admin_profile_:
  resource: '@UmbrellaAdminBundle/config/routes/profile.php'
  prefix: /admin

# User CRUD
umbrella_admin_user_:
  resource: '@UmbrellaAdminBundle/config/routes/user.php'
  prefix: /admin

# Security (login, logout, password resetting)
umbrella_admin_security_:
  resource: '@UmbrellaAdminBundle/config/routes/security.php'
  prefix: /admin
